### ISSUE TITLE
Meta Moderation (10%)

### ISSUE THREAD

**Issue by martafelix13** [goncalo-aroeira/PharmacIST-App#5]
- [ ] Add feature to flag a pharmacy
- [ ] Hide flagged pharmacies from the users who flag them add return feedback (alert)
- [ ] If pharmacy is flagged more than 5 time, hide it from everyone
- [ ] If user flags more than 5 pharmacies, suspend accont.
